"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { Providers } from './wagmi';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import "@/styles/globals.css"
import React, { useEffect, useState } from 'react';
import { Web3Modal } from './web3modal';
import { Wagmi } from './wagmi';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    function handleResize() {
      if (window.innerWidth < 768) {
        setIsMobile(true);
      } else {
        setIsMobile(false);
      }
    }

    window.addEventListener('resize', handleResize);
    handleResize(); // 初始化时执行一次

    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {isMobile ? (
            <Web3Modal>
              <StyledComponentsRegistry>
                {children}
              </StyledComponentsRegistry>
            </Web3Modal>
          ) : (
            <Wagmi>
              <StyledComponentsRegistry>
                {children}
              </StyledComponentsRegistry>
            </Wagmi>
          )}
        </div>
      </body>
    </html>
  )
}
