import dynamic from "next/dynamic";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return [{ id: '10475' }, { id: '10474' }]
}

async function getQuest(id: string) {
  const res = await fetch(`http://192.168.1.10:8087/api/v1/quests/${id}`, { cache: 'no-store' })
  const quest = await res.json()
 
  return quest
}

async function Layout({
  children, params: { id }
}: {
  children: React.ReactNode, params: { id: string }
}) {

  const quest = await getQuest(id);
  

  return (
    <div className="challenge">   
      {children}
    </div>
  )
}

export default dynamic (() => Promise.resolve(Layout), {ssr: false})

